config/routes.rb
Rails.application.routes.draw do
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'

  resources :digs
  resources :assists
  resources :blocks
  resources :passes
  resources :serves
  resources :hits

  resources :games do
    get :increaseHomeScore
    get :decreaseHomeScore
    get :increaseAwayScore
    get :decreaseAwayScore
  end

  resources :users


  resources :teams

  resources :players





end

app/models/assist.rb
class Assist < ApplicationRecord
  has_many :players, foreign_key: "player"
  has_many :games, foreign_key: "game"


  def player_name
    player = Player.find(self.player)
    player.name
  end

  def game_date
    game = Game.find(self.game)
    game.created_at
  end
end

app/models/block.rb
class Block < ApplicationRecord
  has_many :players, foreign_key: "player"
  has_many :games, foreign_key: "game"


  def player_name
    player = Player.find(self.player)
    player.name
  end

  def game_date
    game = Game.find(self.game)
    game.created_at
  end
end

app/models/dig.rb
class Dig < ApplicationRecord
  has_many :players, foreign_key: "player"
  has_many :games, foreign_key: "game"


  def player_name
    player = Player.find(self.player)
    player.name
  end

  def game_date
    game = Game.find(self.game)
    game.created_at
  end
end

app/models/game.rb
class Game < ApplicationRecord
  has_many :teams, foreign_key: "home_team"
  has_many :teams, foreign_key: "away_team"

  def homeTeam
    Team.find(self.home_team)
  end

  def awayTeam
    Team.find(self.away_team)
  end

  def homeTeamName
    team = Team.find(self.home_team)
    team.name
  end

  def awayTeamName
    team = Team.find(self.away_team)
    team.name
  end

  def name
    "#{self.homeTeamName} vs. #{self.awayTeamName}"
  end
end

app/models/hit.rb
class Hit < ApplicationRecord
  has_many :players, foreign_key: "player"
  has_many :games, foreign_key: "game"

  def player_name
    player = Player.find(self.player)
    player.name
  end

  def game_date
    game = Game.find(self.game)
    game.created_at
  end

  def type_of_hit
    if self.level == 1
      "Error"
    elsif self.level == 2
      "Attempt"
    else
      "Kill"
    end
  end


end

app/models/pass.rb
class Pass < ApplicationRecord
  has_many :players, foreign_key: "player"
  has_many :games, foreign_key: "game"


  def player_name
    player = Player.find(self.player)
    player.name
  end

  def game_date
    game = Game.find(self.game)
    game.created_at
  end

  def level_of_pass
    if self.level == 3
      "Perfect"
    elsif self.level == 2
      "Good"
    elsif self.level == 1
      "Bad"
    else
      "Lost Point"
    end
  end
end

app/models/player.rb
class Player < ApplicationRecord
  has_one :teams, foreign_key: "team"

  def team_name
    team = Team.find(self.team)
    team.name
  end

  def games
    team = Team.find(self.team)
    games = Game.where(home_team: team).or(Game.where(away_team: team)).count
  end
end

app/models/serve.rb
class Serve < ApplicationRecord
  has_many :players, foreign_key: "player"
  has_many :games, foreign_key: "game"

  def player_name
    player = Player.find(self.player)
    player.name
  end

  def game_date
    game = Game.find(self.game)
    game.created_at
  end

  def type_of_serve
    if self.level == 1
      "Error"
    elsif self.level == 2
      "Attempt"
    else
      "Ace"
    end
  end
end

app/models/team.rb
class Team < ApplicationRecord
  def players_on_team
    players = Player.where(:team => self.id)
  end

  def team_size
    self.team_size = Player.where(:team => self.id).size
  end
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def new
    # @game = Game.new
  end

  def create
    @game = Game.new(game_params)
    if @game.save
      redirect_to @game
    else
      render "new"
    end
  end

  def index
    @games = Game.all
  end

  def show
    @game = Game.find(params[:id])
  end

  def destroy
    @game = Game.find(params[:id])
    @game.destroy
    redirect_to '/games', :notice => "The game was deleted."
  end

  def increaseHomeScore
    @game = Game.find(params[:game_id])
    @game.increment! :home_score
    redirect_to @game
  end

  def increaseAwayScore
    @game = Game.find(params[:game_id])
    @game.increment! :away_score
    redirect_to @game
  end

  def decreaseHomeScore
    @game = Game.find(params[:game_id])
    @game.decrement! :home_score
    redirect_to @game
  end

  def decreaseAwayScore
    @game = Game.find(params[:game_id])
    @game.decrement! :away_score
    redirect_to @game
  end

  private

  def game_params
    params.require(:game).permit(:home_team, :away_team, :home_score, :away_score)
  end

end

app/helpers/assists_helper.rb
module AssistsHelper
end

app/helpers/blocks_helper.rb
module BlocksHelper
end

app/helpers/digs_helper.rb
module DigsHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/hits_helper.rb
module HitsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/passes_helper.rb
module PassesHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/serves_helper.rb
module ServesHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/games/index.html.erb
<div class="container">
  <h1>Games</h1>
  <table id="table">
    <tr>
      <th>Home Team</th>
      <th></th>
      <th>Away Team</th>
      <th>Run/Resume</th>
      <th>Delete</th>
    </tr>
    <% for game in @games %> <!-- In writen rails to call on database -->
      <tr>
        <td><%= game.homeTeamName %></td>
        <td>vs.</td>
        <td><%= game.awayTeamName %></td>
        <td><%= link_to "Start/Resume", game_path(game)%></td> <!-- TODO: Change this to better wording -->
        <td><%= link_to "Delete",  game_path(game), :method => :delete %></td>
      </tr>
    <% end %>
  </table>
  <br>
  <%= link_to "Create New Game", new_game_path, class: "button game-button" %>
</div>

app/views/games/new.html.erb
<div class="container">
  <div class="row">
    <h1 class="col-12">Create New Game</h1>
  </div>
  <div class="row new-border">
    <%= form_for :game, url: games_path do |f| %>
      <p>
        <%= f.label :home_team %><br>
        <%= f.collection_select :home_team, Team.all, :id, :name %>
      </p>
      <p>
        <%= f.label :away_team %><br>
        <%= f.collection_select :away_team, Team.all, :id, :name %>
      </p>
      <%= f.hidden_field :home_score, value: 0 %>
      <%= f.hidden_field :away_score, value: 0 %>
      <p>
        <%= f.submit "New Game", :class => "button" %>
      </p>
    <% end %>
  </div>
</div>

app/views/games/show.html.erb
<%= stylesheet_link_tag "games" %>

<div class="container">
  <div class="game-border">
    <h1>Game</h1>
    <div class="row team">
      <div class="col-4">
        <h3><%= @game.homeTeamName %></h3>
        <p>Home Team</p>
      </div>
      <div class="col-1">
        <%= link_to '▲', game_increaseHomeScore_path(@game.id), :id => "increase", :class => "value-button"%>
        <div id="number"><%= @game.home_score %></div>
        <%= link_to '▼', game_decreaseHomeScore_path(@game.id), :id => "decrease", :class => "value-button"%>
      </div>
      <div class="offset-1 col-1">
        <%= link_to '▲', game_increaseAwayScore_path(@game.id), :id => "increase", :class => "value-button"%>
        <div id="number"><%= @game.away_score %></div>
        <%= link_to '▼', game_decreaseAwayScore_path(@game.id), :id => "decrease", :class => "value-button"%>
      </div>
      <div class="col-4">
        <h3><%= @game.awayTeamName %></h3>
        <p> Away Team</p>
      </div>
    </div>
  </div>
 <%= render 'players/stats' %>
</div>