config/routes.rb
Rails.application.routes.draw do
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'

  resources :digs
  resources :assists
  resources :blocks
  resources :passes
  resources :serves
  resources :hits

  resources :games do
    get :increaseHomeScore
    get :decreaseHomeScore
    get :increaseAwayScore
    get :decreaseAwayScore
  end

  resources :users


  resources :teams

  resources :players





end

app/models/assist.rb
class Assist < ApplicationRecord
  has_many :players, foreign_key: "player"
  has_many :games, foreign_key: "game"


  def player_name
    player = Player.find(self.player)
    player.name
  end

  def game_date
    game = Game.find(self.game)
    game.created_at
  end
end

app/models/block.rb
class Block < ApplicationRecord
  has_many :players, foreign_key: "player"
  has_many :games, foreign_key: "game"


  def player_name
    player = Player.find(self.player)
    player.name
  end

  def game_date
    game = Game.find(self.game)
    game.created_at
  end
end

app/models/dig.rb
class Dig < ApplicationRecord
  has_many :players, foreign_key: "player"
  has_many :games, foreign_key: "game"


  def player_name
    player = Player.find(self.player)
    player.name
  end

  def game_date
    game = Game.find(self.game)
    game.created_at
  end
end

app/models/game.rb
class Game < ApplicationRecord
  has_many :teams, foreign_key: "home_team"
  has_many :teams, foreign_key: "away_team"

  def homeTeam
    Team.find(self.home_team)
  end

  def awayTeam
    Team.find(self.away_team)
  end

  def homeTeamName
    team = Team.find(self.home_team)
    team.name
  end

  def awayTeamName
    team = Team.find(self.away_team)
    team.name
  end

  def name
    "#{self.homeTeamName} vs. #{self.awayTeamName}"
  end
end

app/models/hit.rb
class Hit < ApplicationRecord
  has_many :players, foreign_key: "player"
  has_many :games, foreign_key: "game"

  def player_name
    player = Player.find(self.player)
    player.name
  end

  def game_date
    game = Game.find(self.game)
    game.created_at
  end

  def type_of_hit
    if self.level == 1
      "Error"
    elsif self.level == 2
      "Attempt"
    else
      "Kill"
    end
  end


end

app/models/pass.rb
class Pass < ApplicationRecord
  has_many :players, foreign_key: "player"
  has_many :games, foreign_key: "game"


  def player_name
    player = Player.find(self.player)
    player.name
  end

  def game_date
    game = Game.find(self.game)
    game.created_at
  end

  def level_of_pass
    if self.level == 3
      "Perfect"
    elsif self.level == 2
      "Good"
    elsif self.level == 1
      "Bad"
    else
      "Lost Point"
    end
  end
end

app/models/player.rb
class Player < ApplicationRecord
  has_one :teams, foreign_key: "team"

  def team_name
    team = Team.find(self.team)
    team.name
  end

  def games
    team = Team.find(self.team)
    games = Game.where(home_team: team).or(Game.where(away_team: team)).count
  end
end

app/models/serve.rb
class Serve < ApplicationRecord
  has_many :players, foreign_key: "player"
  has_many :games, foreign_key: "game"

  def player_name
    player = Player.find(self.player)
    player.name
  end

  def game_date
    game = Game.find(self.game)
    game.created_at
  end

  def type_of_serve
    if self.level == 1
      "Error"
    elsif self.level == 2
      "Attempt"
    else
      "Ace"
    end
  end
end

app/models/team.rb
class Team < ApplicationRecord
  def players_on_team
    players = Player.where(:team => self.id)
  end

  def team_size
    self.team_size = Player.where(:team => self.id).size
  end
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController

  def create
    @player = Player.new(player_params)
    if @player.save
      redirect_to Team.find(@player.team)
    else
      render 'new'
    end
  end

  def index
    @players = Player.all
  end

  def show
    @player = Player.find(params[:id])
  end

  def destroy
    @player = Player.find(params[:id])
    @player.destroy
    redirect_to '/players', :notice => "The game was deleted."
  end

  private

  def player_params
    params.require(:player).permit(:name, :age, :height, :team)
  end
end

app/helpers/assists_helper.rb
module AssistsHelper
end

app/helpers/blocks_helper.rb
module BlocksHelper
end

app/helpers/digs_helper.rb
module DigsHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/hits_helper.rb
module HitsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/passes_helper.rb
module PassesHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/serves_helper.rb
module ServesHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/players/index.html.erb
<div class="container">
  <h1>Players</h1>
  <p> For players by team, you should go to the teams tab. Select view on your
    players team and a list of all players on that team will appear. </p>
  <table id="table">
    <tr>
      <th>Player Name</th>
      <th>Age</th>
      <th>Height</th>
      <th>Team</th>
      <th>Player Stats</th>
      <th>Delete</th>
    </tr>
    <% for player in @players %>
      <tr>
        <td><%= player.name %></td>
        <td><%= player.age %></td>
        <td><%= player.height %></td>
        <td><%= player.team_name %></td>
        <td><%= link_to "Stats", player_path(player) %></td>
        <td><%= link_to "Delete",  player_path(player), :method => :delete %></td>
      </tr>
    <% end %>
  </table>
  <br>
  <%= link_to "Create New Player", new_player_path, :class => "button player-button" %>
</div>

app/views/players/new.html.erb
<div class="container">
  <div class="row">
    <h1 class="col-12">Create a New Player</h1>
  </div>
  <div class="row new-border">
    <%= form_for :player, url: players_path do |f| %>
      <p>
        <%= f.label :Name %>
        <%= f.text_field :name %>
      </p>
      <p>
        <%= f.label :age %>
        <%= f.number_field :age %>
      </p>
      <p>
        <%= f.label :height %>
        <%= f.text_field :height %>
      </p>
      <p>
        <%= f.label :team %>
        <%= f.collection_select :team, Team.all, :id, :name %>
      </p>
      <p>
        <%= f.submit "New Player", :class => "button" %>
      </p>
    <% end %>
  </div>
</div>

app/views/players/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-6">
      <div class="row">
        <h1 class="col-12"><%= @player.name %></h1>
      </div>
    </div>
    <div class="col-6">
      <div class="row">
        <h3 class="col-2">Age: </h3>
        <h3 class="col-3"><%= @player.age %></h3>
        <h3 class="col-3">height: </h3>
        <h3 class="col-3"><%= @player.height %></h3>
      </div>
      <div class="row">
        <h3 class="col-3">Team: </h3>
        <h3 class="col-8"><%= @player.team_name %>
      </div>
    </div>
  </div>
  <div class="row">
    <h2>Totals of All Stats</h2>
    <table id="table">
      <tr>
        <th>Digs</th>
        <th>Assists</th>
        <th>Blocks</th>
        <th>Passes</th>
        <th>Average Passing Level</th>
        <th>Serves</th>
        <th>Serving Percentage</th>
        <th>His</th>
        <th>Hiting Percentage</th>
      </tr>
      <tr>
        <td><%= Dig.where(player: @player.id).count %></td>
        <td><%= Assist.where(player: @player.id).count %></td>
        <td><%= Block.where(player: @player.id).count %></td>
        <td><%= Pass.where(player: @player.id).count %></td>
        <td><%= Pass.where(player: @player.id).average(:level) %></td>
        <td><%= Serve.where(player: @player.id).count %></td>
        <% if Serve.where(player: @player.id).count == 0 %>
          <td>0</td>
        <% else %>
          <td><%= (((Serve.where(player: @player.id, level: 3).count - Serve.where(player: @player.id, level: 1).count)).fdiv(Serve.where(player: @player.id).count))*100 %>%</td>
        <% end %>
        <td><%= Hit.where(player: @player.id).count %></td>
        <% if Hit.where(player: @player.id).count == 0 %>
          <td>0</td>
        <% else %>
          <td><%= (((Hit.where(player: @player.id, level: 3).count - Hit.where(player: @player.id, level: 1).count)).fdiv(Hit.where(player: @player.id).count))*100 %>%</td>
        <% end %>
      </tr>
    </table>
    <h2>Averages Per Game</h2>
    <table id="table">
      <tr>
        <th>Digs</th>
        <th>Assists</th>
        <th>Blocks</th>
        <th>Average Passing Level</th>
        <th>Serving Percentage</th>
        <th>Hiting Percentage</th>
      </tr>
      <tr>
        <td><%= Dig.where(player: @player.id).count/@player.games %></td>
        <td><%= Assist.where(player: @player.id).count/@player.games %></td>
        <td><%= Block.where(player: @player.id).count/@player.games %></td>
        <td><%= Pass.where(player: @player.id).average(:level)/@player.games %></td>
        <% if Serve.where(player: @player.id).count == 0 %>
          <td>0</td>
        <% else %>
          <td><%= ((((Serve.where(player: @player.id, level: 3).count - Serve.where(player: @player.id, level: 1).count)).fdiv(Serve.where(player: @player.id).count))).fdiv(@player.games)*100 %>%</td>
        <% end %>
        <% if Hit.where(player: @player.id).count == 0 %>
          <td>0</td>
        <% else %>
          <td><%= ((((Hit.where(player: @player.id, level: 3).count - Hit.where(player: @player.id, level: 1).count)).fdiv(Hit.where(player: @player.id).count)).fdiv(@player.games))*100 %>%</td>
        <% end %>
      </tr>
    </table>
  </div>
</div>