config/routes.rb
Rails.application.routes.draw do
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'

  resources :digs
  resources :assists
  resources :blocks
  resources :passes
  resources :serves
  resources :hits

  resources :games do
    get :increaseHomeScore
    get :decreaseHomeScore
    get :increaseAwayScore
    get :decreaseAwayScore
  end

  resources :users


  resources :teams

  resources :players





end

app/models/assist.rb
class Assist < ApplicationRecord
  has_many :players, foreign_key: "player"
  has_many :games, foreign_key: "game"


  def player_name
    player = Player.find(self.player)
    player.name
  end

  def game_date
    game = Game.find(self.game)
    game.created_at
  end
end

app/models/block.rb
class Block < ApplicationRecord
  has_many :players, foreign_key: "player"
  has_many :games, foreign_key: "game"


  def player_name
    player = Player.find(self.player)
    player.name
  end

  def game_date
    game = Game.find(self.game)
    game.created_at
  end
end

app/models/dig.rb
class Dig < ApplicationRecord
  has_many :players, foreign_key: "player"
  has_many :games, foreign_key: "game"


  def player_name
    player = Player.find(self.player)
    player.name
  end

  def game_date
    game = Game.find(self.game)
    game.created_at
  end
end

app/models/game.rb
class Game < ApplicationRecord
  has_many :teams, foreign_key: "home_team"
  has_many :teams, foreign_key: "away_team"

  def homeTeam
    Team.find(self.home_team)
  end

  def awayTeam
    Team.find(self.away_team)
  end

  def homeTeamName
    team = Team.find(self.home_team)
    team.name
  end

  def awayTeamName
    team = Team.find(self.away_team)
    team.name
  end

  def name
    "#{self.homeTeamName} vs. #{self.awayTeamName}"
  end
end

app/models/hit.rb
class Hit < ApplicationRecord
  has_many :players, foreign_key: "player"
  has_many :games, foreign_key: "game"

  def player_name
    player = Player.find(self.player)
    player.name
  end

  def game_date
    game = Game.find(self.game)
    game.created_at
  end

  def type_of_hit
    if self.level == 1
      "Error"
    elsif self.level == 2
      "Attempt"
    else
      "Kill"
    end
  end


end

app/models/pass.rb
class Pass < ApplicationRecord
  has_many :players, foreign_key: "player"
  has_many :games, foreign_key: "game"


  def player_name
    player = Player.find(self.player)
    player.name
  end

  def game_date
    game = Game.find(self.game)
    game.created_at
  end

  def level_of_pass
    if self.level == 3
      "Perfect"
    elsif self.level == 2
      "Good"
    elsif self.level == 1
      "Bad"
    else
      "Lost Point"
    end
  end
end

app/models/player.rb
class Player < ApplicationRecord
  has_one :teams, foreign_key: "team"

  def team_name
    team = Team.find(self.team)
    team.name
  end

  def games
    team = Team.find(self.team)
    games = Game.where(home_team: team).or(Game.where(away_team: team)).count
  end
end

app/models/serve.rb
class Serve < ApplicationRecord
  has_many :players, foreign_key: "player"
  has_many :games, foreign_key: "game"

  def player_name
    player = Player.find(self.player)
    player.name
  end

  def game_date
    game = Game.find(self.game)
    game.created_at
  end

  def type_of_serve
    if self.level == 1
      "Error"
    elsif self.level == 2
      "Attempt"
    else
      "Ace"
    end
  end
end

app/models/team.rb
class Team < ApplicationRecord
  def players_on_team
    players = Player.where(:team => self.id)
  end

  def team_size
    self.team_size = Player.where(:team => self.id).size
  end
end

app/models/user.rb
class User < ApplicationRecord
end

app/helpers/blocks_helper.rb
module BlocksHelper
end

app/helpers/digs_helper.rb
module DigsHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/hits_helper.rb
module HitsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/passes_helper.rb
module PassesHelper
end

app/helpers/serves_helper.rb
module ServesHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <title>MetaSports</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="navigation-bar">
      <div class="container">
        <div class="row">
          <div class="col-2">
            <img class="logo-header" src="/logos/volleyball2.3.png" alt="METASPORTS" height="68">
          </div>
            <%= link_to "Home", root_path, :class => "nav-button header col-2" %>
            <%= link_to "Players", players_path, :class => "nav-button header col-2"  %>
            <%= link_to "Teams", teams_path, :class => "nav-button header col-2"  %>
            <%= link_to "Games", games_path, :class => "nav-button header col-2"  %>
        </div>
      </div>
    </div>
    <%= yield %>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>